version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - amazonmq
  - dbname
  - Fargate
  - gcloud
  - memorydb
  - noinput
  - Oncall
  - RABBITMQ
ignoreWords: []
import: []
