version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - amazonmq
  - dbname
  - dotenvx
  - elasticloadbalancingv2
  - Fargate
  - gcloud
  - ingester
  - memorydb
  - mydb
  - noinput
  - Oncall
  - RABBITMQ
  - tsup
  - uwsgi
ignoreWords: []
import: []
